"""Measure open/closed state histories for tracked r_index=0 footpoints.

Mode ``crossings`` reads model-tracked footpoints from
``track_crossings_connectivity.py``. Mode ``lct`` reads LCT-tracked
footpoints from ``track_footpoints_lct.py``. At every time, states are sampled
only from `rindex0_open_closed_map`, i.e. the map traced from r_index=0.

Outputs: `tracked_open_closed_states.<mode>.npz`. Invalid coordinates are
flagged by `footpoint_valid`; their stored state is 0 but is excluded from
state-transition calculations.
"""

from __future__ import annotations

from pathlib import Path
import re

import numpy as np

from config import FULL_TRACK_OPEN_DIR, OPEN_CLOSED_DIR, WORK_ROOT


MODE = "crossings"  # "crossings" or "lct"
LCT_TRACK_DIR = WORK_ROOT / "lct_surface_tracks"
MODEL_TRACK_DIR = FULL_TRACK_OPEN_DIR
OUTPUT_DIR = WORK_ROOT / "tracked_open_closed_states"
TIME_TOL_HOURS = 1.0e-6

LCT_PATTERN = re.compile(r"^lct_footpoint_track\.time\.([0-9]+(?:\.[0-9]+)?)\.npz$")
MODEL_PATTERN = re.compile(r"^track_open\.time\.([0-9]+(?:\.[0-9]+)?)\.r0\.([0-9]+(?:\.[0-9]+)?)\.npz$")


def output_filename() -> Path:
    """Return the state-history output file for the configured source mode."""
    return OUTPUT_DIR / f"tracked_open_closed_states.{MODE}.npz"


def discover_tracks() -> list[tuple[float, Path]]:
    """Return source track files ordered by time."""
    directory = MODEL_TRACK_DIR if MODE == "crossings" else LCT_TRACK_DIR
    pattern = MODEL_PATTERN if MODE == "crossings" else LCT_PATTERN
    if not directory.is_dir():
        raise FileNotFoundError(directory)
    entries = []
    for filename in directory.iterdir():
        match = pattern.fullmatch(filename.name)
        if match is not None:
            entries.append((float(match.group(1)), filename))
    entries.sort(key=lambda item: item[0])
    if not entries:
        raise FileNotFoundError(f"No {MODE} track files in {directory}")
    return entries


def open_closed_filename(time_hours: float) -> Path:
    """Return r_index=0 topology map filename for one time."""
    return OPEN_CLOSED_DIR / f"open_closed_time.{time_hours:.2f}.npz"


def load_track_footpoints(filename: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load persistent IDs and r_index=0 footpoint coordinates for one mode."""
    if MODE == "crossings":
        keys = ("id", "inner_theta", "inner_phi")
    else:
        keys = ("id", "theta_rad", "phi_rad")
    with np.load(filename, allow_pickle=False) as data:
        missing = [key for key in keys if key not in data]
        if missing:
            raise KeyError(f"Missing {missing} in {filename}")
        ids = np.asarray(data[keys[0]], dtype=np.int64)
        theta = np.asarray(data[keys[1]], dtype=float)
        phi = np.asarray(data[keys[2]], dtype=float) % (2.0 * np.pi)
    if ids.ndim != 1 or theta.shape != ids.shape or phi.shape != ids.shape:
        raise ValueError(f"Incompatible ID/theta/phi shapes in {filename}")
    return ids, theta, phi


def load_rindex0_open_closed(filename: Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load only the topology map generated by r_index=0 trace seeds."""
    required = ("theta", "phi", "rindex0_open_closed_map")
    with np.load(filename, allow_pickle=False) as data:
        missing = [key for key in required if key not in data]
        if missing:
            raise KeyError(f"Missing {missing} in {filename}")
        theta = np.asarray(data["theta"], dtype=float)
        phi = np.asarray(data["phi"], dtype=float)
        labels = np.asarray(data["rindex0_open_closed_map"], dtype=np.int8)
    if labels.shape != (theta.size, phi.size):
        raise ValueError(f"Topology shape mismatch in {filename}")
    return theta, phi, labels


def nearest_grid_indices(values: np.ndarray, grid: np.ndarray, periodic: bool) -> np.ndarray:
    """Return nearest monotonic-grid indices, with optional 2π periodicity."""
    values = np.asarray(values, dtype=float)
    if periodic:
        values = values % (2.0 * np.pi)
    upper = np.searchsorted(grid, values, side="left")
    lower = np.clip(upper - 1, 0, grid.size - 1)
    upper = np.clip(upper, 0, grid.size - 1)
    if periodic:
        lower_distance = np.abs(np.angle(np.exp(1j * (values - grid[lower]))))
        upper_distance = np.abs(np.angle(np.exp(1j * (values - grid[upper]))))
    else:
        lower_distance = np.abs(values - grid[lower])
        upper_distance = np.abs(values - grid[upper])
    return np.where(upper_distance < lower_distance, upper, lower)


def sample_states(theta: np.ndarray, phi: np.ndarray, map_theta: np.ndarray, map_phi: np.ndarray, labels: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Sample categorical r_index=0 states at each valid footpoint."""
    valid = np.isfinite(theta) & np.isfinite(phi)
    states = np.zeros(theta.size, dtype=np.int8)
    if np.any(valid):
        theta_index = nearest_grid_indices(theta[valid], map_theta, periodic=False)
        phi_index = nearest_grid_indices(phi[valid], map_phi, periodic=True)
        states[valid] = labels[theta_index, phi_index]
    return states, valid


def state_change(previous: np.ndarray, current: np.ndarray, previous_valid: np.ndarray, current_valid: np.ndarray) -> np.ndarray:
    """Encode 0=unchanged, -1=open-to-closed, +1=closed-to-open."""
    change = np.zeros(current.size, dtype=np.int8)
    valid = previous_valid & current_valid
    was_open = np.abs(previous) == 1
    is_open = np.abs(current) == 1
    change[valid & was_open & ~is_open] = -1
    change[valid & ~was_open & is_open] = 1
    return change


def main() -> None:
    """Create r_index=0 open/closed state and transition histories for all IDs."""
    if MODE not in {"crossings", "lct"}:
        raise ValueError("MODE must be 'crossings' or 'lct'.")
    entries = discover_tracks()
    times = np.asarray([time for time, _ in entries], dtype=float)
    reference_ids = None
    footpoint_theta = []
    footpoint_phi = []
    states_by_time = []
    valid_by_time = []
    for time_hours, track_file in entries:
        ids, theta, phi = load_track_footpoints(track_file)
        if reference_ids is None:
            reference_ids = ids
        elif not np.array_equal(ids, reference_ids):
            raise ValueError(f"ID ordering differs from initial time: {track_file}")
        map_theta, map_phi, labels = load_rindex0_open_closed(open_closed_filename(time_hours))
        states, valid = sample_states(theta, phi, map_theta, map_phi, labels)
        footpoint_theta.append(theta)
        footpoint_phi.append(phi)
        states_by_time.append(states)
        valid_by_time.append(valid)
    theta_array = np.column_stack(footpoint_theta)
    phi_array = np.column_stack(footpoint_phi)
    state_array = np.column_stack(states_by_time)
    valid_array = np.column_stack(valid_by_time)
    change_array = np.zeros_like(state_array, dtype=np.int8)
    for itime in range(1, times.size):
        change_array[:, itime] = state_change(
            state_array[:, itime - 1], state_array[:, itime],
            valid_array[:, itime - 1], valid_array[:, itime],
        )
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_filename(),
        mode=MODE,
        time_hours=times,
        id=reference_ids,
        footpoint_theta_rad=theta_array.astype(np.float32),
        footpoint_phi_rad=phi_array.astype(np.float32),
        footpoint_longitude_deg=(np.degrees(phi_array) % 360.0).astype(np.float32),
        footpoint_latitude_deg=(90.0 - np.degrees(theta_array)).astype(np.float32),
        open_closed_state=state_array,
        open_closed_state_change=change_array,
        footpoint_valid=valid_array,
        map_key="rindex0_open_closed_map",
    )
    print(f"Saved {MODE} open/closed histories:\n  {output_filename()}")


if __name__ == "__main__":
    main()
