"""Small helpers for identifying generated scientific figures.

This module does not generate files itself.
"""

from __future__ import annotations


def add_figure_provenance(figure, program_name: str) -> None:
    """Add a compact lower-right provenance label to a Matplotlib figure."""
    figure.text(
        0.99,
        0.01,
        f"Generated by: {program_name}",
        ha="right",
        va="bottom",
        fontsize=7,
        color="0.25",
        alpha=0.8,
    )
